sudo: false
language: generic
matrix:
  include:
  - compiler: GHC 7.0.1
    env: GHC_VERSION=7.0.1 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.0.1
        sources:
        - hvr-ghc
  - compiler: GHC 7.0.2
    env: GHC_VERSION=7.0.2 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.0.2
        sources:
        - hvr-ghc
  - compiler: GHC 7.0.3
    env: GHC_VERSION=7.0.3 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.0.3
        sources:
        - hvr-ghc
  - compiler: GHC 7.0.4
    env: GHC_VERSION=7.0.4 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.0.4
        sources:
        - hvr-ghc
  - compiler: GHC 7.2.2
    env: GHC_VERSION=7.2.2 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.2.2
        sources:
        - hvr-ghc
  - compiler: GHC 7.4.1
    env: GHC_VERSION=7.4.1 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.4.1
        sources:
        - hvr-ghc
  - compiler: GHC 7.4.2
    env: GHC_VERSION=7.4.2 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.4.2
        sources:
        - hvr-ghc
  - compiler: GHC 7.6.1
    env: GHC_VERSION=7.6.1 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.6.1
        sources:
        - hvr-ghc
  - compiler: GHC 7.6.2
    env: GHC_VERSION=7.6.2 CABAL_VERSION=1.16
    addons:
      apt:
        packages:
        - cabal-install-1.16
        - ghc-7.6.2
        sources:
        - hvr-ghc
  - compiler: GHC 7.6.3
    env: GHC_VERSION=7.6.3 CABAL_VERSION=1.18
    addons:
      apt:
        packages:
        - cabal-install-1.18
        - ghc-7.6.3
        sources:
        - hvr-ghc
  - compiler: GHC 7.8.1
    env: GHC_VERSION=7.8.1 CABAL_VERSION=1.18
    addons:
      apt:
        packages:
        - cabal-install-1.18
        - ghc-7.8.1
        sources:
        - hvr-ghc
  - compiler: GHC 7.8.2
    env: GHC_VERSION=7.8.2 CABAL_VERSION=1.18
    addons:
      apt:
        packages:
        - cabal-install-1.18
        - ghc-7.8.2
        sources:
        - hvr-ghc
  - compiler: GHC 7.8.3
    env: GHC_VERSION=7.8.3 CABAL_VERSION=1.18
    addons:
      apt:
        packages:
        - cabal-install-1.18
        - ghc-7.8.3
        sources:
        - hvr-ghc
  - compiler: GHC 7.8.4
    env: GHC_VERSION=7.8.4 CABAL_VERSION=1.18
    addons:
      apt:
        packages:
        - cabal-install-1.18
        - ghc-7.8.4
        sources:
        - hvr-ghc
  - compiler: GHC 7.10.1
    env: GHC_VERSION=7.10.1 CABAL_VERSION=1.22
    addons:
      apt:
        packages:
        - cabal-install-1.22
        - ghc-7.10.1
        sources:
        - hvr-ghc
  - compiler: GHC 7.10.2
    env: GHC_VERSION=7.10.2 CABAL_VERSION=1.22
    addons:
      apt:
        packages:
        - cabal-install-1.22
        - ghc-7.10.2
        sources:
        - hvr-ghc
  - compiler: GHC 7.10.3
    env: GHC_VERSION=7.10.3 CABAL_VERSION=1.22
    addons:
      apt:
        packages:
        - cabal-install-1.22
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - compiler: GHC 8.0.1
    env: GHC_VERSION=8.0.1 CABAL_VERSION=1.24
    addons:
      apt:
        packages:
        - cabal-install-1.24
        - ghc-8.0.1
        sources:
        - hvr-ghc
  - compiler: GHC 8.0.2
    env: GHC_VERSION=8.0.2 CABAL_VERSION=1.24
    addons:
      apt:
        packages:
        - cabal-install-1.24
        - ghc-8.0.2
        sources:
        - hvr-ghc
  - compiler: GHC 8.2.1
    env: GHC_VERSION=8.2.1 CABAL_VERSION=2.0
    addons:
      apt:
        packages:
        - cabal-install-2.0
        - ghc-8.2.1
        sources:
        - hvr-ghc
  - compiler: GHC 8.2.2
    env: GHC_VERSION=8.2.2 CABAL_VERSION=2.0
    addons:
      apt:
        packages:
        - cabal-install-2.0
        - ghc-8.2.2
        sources:
        - hvr-ghc
before_install:
- export PATH=/opt/ghc/$GHC_VERSION/bin:/opt/cabal/$CABAL_VERSION/bin:$HOME/.cabal/bin:$PATH
install:
- cabal --version
- ghc --version
- travis_retry cabal update
- grep jobs ${HOME}/.cabal/config
- ! 'sed -i ''s/^jobs:.*/jobs: 2/'' ${HOME}/.cabal/config'
- grep jobs ${HOME}/.cabal/config
- cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
- cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
  --show-details=always
