name:           nanospec
version:        0.2.1
license:        MIT
license-file:   LICENSE
copyright:      (c) 2012-2015 Simon Hengel
author:         Simon Hengel <sol@typeful.net>
maintainer:     Simon Hengel <sol@typeful.net>
category:       Testing
synopsis:       A lightweight implementation of a subset of Hspec's API
description:    A lightweight implementation of a subset of Hspec's API with minimal dependencies.

github: hspec/nanospec

ghc-options: -Wall

dependencies:
  base: 4.*

source-dirs: src

library:
  exposed: no

tests:
  spec:
    main: Test/HspecSpec.hs
    cpp-options: -DTEST
    source-dirs: test
    dependencies:
      - hspec >= 1.3
      - silently >= 1.2.4
